-- Startbestand der Speisekarte, 1:1 aus dem bisherigen HTML uebernommen.
-- Stand: Canva-PDF von Goekhan Yavuz, 19.08.2026.

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('vorspeisen','Vorspeisen & Salate',10,1,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('vorspeisen-1','vorspeisen','Suppen',NULL,10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-1-1','vorspeisen-1','Tomatencremesuppe',NULL,'7,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-1-2','vorspeisen-1','Linsensuppe',NULL,'7,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-1-3','vorspeisen-1','Rinderkraftbrühe','mit hausgemachter Maultasche','8,50 €',30,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('vorspeisen-2','vorspeisen','Vorspeisen',NULL,20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-1','vorspeisen-2','Salat',NULL,'7,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-2','vorspeisen-2','Bruschetta','mit frischem Rucola','8,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-3','vorspeisen-2','Büffelmozzarella','mit hausgemachtem Pesto, Rucola und Kirschtomaten','9,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-4','vorspeisen-2','Buratta','mit gebratener Zucchini, Tomaten, Rucola und Pinienkernen','14,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-5','vorspeisen-2','Garnelen','mit Knoblauch im Tontopf','14,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-2-6','vorspeisen-2','Carpaccio','mit Rucola, hausgemachtem Pesto und Grana Padano','16,50 €',60,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('vorspeisen-3','vorspeisen','Salate',NULL,30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-1','vorspeisen-3','Salat Schwäbisch','mit hausgemachten Maultaschen','19,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-2','vorspeisen-3','Salat Veggie','mit gegrilltem Gemüse und Feta','22,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-3','vorspeisen-3','Salat Gambas','mit Garnelen und Ananas','24,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-4','vorspeisen-3','Salat Omega','mit Lachsfilet und Avocado','24,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-5','vorspeisen-3','Salat Steakhouse','mit Rindersteakstreifen','24,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('vorspeisen-3-6','vorspeisen-3','Salat Wien','mit panierten Kalbschnitzelstreifen','24,50 €',60,1);

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('teigwaren','Teigwaren',20,1,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('teigwaren-1','teigwaren','Pasta','Pasta wählbar zwischen Spaghetti, Penne und Rigatoni.',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-1','teigwaren-1','Pasta Arrabbiata','mit scharfer Tomatensoße','12,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-2','teigwaren-1','Pasta Caprese','mit Büffelmozzarella in Tomaten-Sahne-Soße','14,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-3','teigwaren-1','Pasta Veggie','mit gegrilltem Gemüse in Tomaten-Sahne-Soße','16,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-4','teigwaren-1','Pasta Gambas','mit Garnelen in Limetten-Sahne-Soße','18,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-5','teigwaren-1','Pasta Omega','mit Lachsfilet und Spinat in Weißwein-Sahne-Soße','18,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-1-6','teigwaren-1','Pasta Steakhouse','mit Rinderstreifen in Tomaten-Sahne-Soße','18,50 €',60,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('teigwaren-2','teigwaren','Schwäbische Teigwaren',NULL,20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-2-1','teigwaren-2','Portion Spätzle','handgeschabt mit Zwiebelschmelze','9,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-2-2','teigwaren-2','Käsespätzle','handgeschabt mit Emmentaler, Bergkäse und Zwiebelschmelze','13,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-2-3','teigwaren-2','Maultaschen','hausgemacht mit Zwiebelschmelze','13,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('teigwaren-2-4','teigwaren-2','Manti','kleine mit Hackfleisch gefüllte Teigtaschen mit Knoblauch-Joghurt-Soße und in Butter geschmolzenem Tomatenmark','16,50 €',40,1);

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('steak','Steak & Burger',30,1,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('steak-1','steak','Steak auf heißem Stein',NULL,10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-1-1','steak-1','Hüftesteak','mager und intensiv','200 g 22,00 €
300 g 29,00 €
400 g 36,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-1-2','steak-1','Rumpsteak','mit typischem Fettrand','200 g 25,00 €
300 g 33,00 €
400 g 41,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-1-3','steak-1','Filet','zart und mager','200 g 31,00 €
300 g 40,00 €
400 g 49,00 €',30,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('steak-2','steak','Burger','100 g hausgemachtes Patty.',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-1','steak-2','Hamburger',NULL,'11,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-2','steak-2','Cheeseburger','mit Cheddar','12,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-3','steak-2','Chili-Cheeseburger','mit Cheddar und Jalapeños','12,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-4','steak-2','BBQ-Burger','mit BBQ-Soße und Bacon','12,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-5','steak-2','Veggie-Burger','mit vegetarischem Patty','11,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-2-6','steak-2','Patty extra',NULL,'4,00 €',60,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('steak-3','steak','Beilagen',NULL,30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-3-1','steak-3','Pommes',NULL,'5,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-3-2','steak-3','Süßkartoffel-Pommes',NULL,'6,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-3-3','steak-3','Gemüse',NULL,'7,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('steak-3-4','steak-3','Salat',NULL,'7,00 €',40,1);

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('klassiker','Klassiker',40,1,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('klassiker-1','klassiker','Klassiker',NULL,10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-1','klassiker-1','Schweizer Wurstsalat','Wurst von der Metzgerei Seyb mit Gürkchen und Emmentaler','15,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-2','klassiker-1','Schweineschnitzel „Wiener Art“','hausgemacht vom Rücken, mit handgeschabten Spätzle oder Pommes','19,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-3','klassiker-1','Garnelenpfanne','Garnelen mit gegrilltem Gemüse und Basmati-Reis','29,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-4','klassiker-1','Fleischpfanne','geschnetzeltes Rindersteak mit gegrilltem Gemüse und Basmati-Reis','29,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-5','klassiker-1','Lachsfilet','mit Spinat und Basmati-Reis in Weißwein-Soße','29,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-6','klassiker-1','Rostbraten','mit Maultasche und Lemberger-Jus, dazu handgeschabte Spätzle oder Bratkartoffeln','32,50 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-7','klassiker-1','Wiener Schnitzel vom Kalb','hausgemacht vom Rücken, mit Preiselbeeren und handgeschabten Spätzle oder Bratkartoffeln','32,50 €',70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('klassiker-1-8','klassiker-1','Doradenfilet','mit Grillgemüse, Bratkartoffeln und Honig-Senf-Soße','32,50 €',80,1);

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('suesses','Süßes',50,1,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('suesses-1','suesses','Süßes',NULL,10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('suesses-1-1','suesses-1','Portion Vanilleeis','2 Kugeln mit Schoko- oder Beerensoße','5,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('suesses-1-2','suesses-1','Panna Cotta','mit hausgemachter Erdbeersoße, gerösteten Haselnüssen und Erdbeere','7,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('suesses-1-3','suesses-1','Crème brûlée','hausgemacht mit Zitronenzeste und Vanille','7,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('suesses-1-4','suesses-1','Heiße Beeren','3 Kugeln Vanilleeis mit heißen Beeren und Schlagsahne','9,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('suesses-1-5','suesses-1','Pancake','mit Vanilleeis, Beeren, Bananen und hausgemachter Schokoladensoße','12,50 €',50,1);

INSERT OR IGNORE INTO menu_tabs (id,title,sort,cols,active) VALUES ('getraenke','Getränke',60,2,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-1','getraenke','Cocktails',NULL,10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-1','getraenke-1','Aperol Sour',NULL,'8,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-2','getraenke-1','Whiskey Sour',NULL,'8,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-3','getraenke-1','Roseano Sour',NULL,'8,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-4','getraenke-1','Gin Fizz',NULL,'8,50 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-5','getraenke-1','Gin Basil Smash',NULL,'8,50 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-6','getraenke-1','Negroni',NULL,'9,50 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-7','getraenke-1','Americano',NULL,'9,50 €',70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-8','getraenke-1','Old Fashioned',NULL,'9,50 €',80,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-9','getraenke-1','Caipirinha',NULL,'9,50 €',90,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-10','getraenke-1','Cuba Libre',NULL,'9,50 €',100,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-11','getraenke-1','Mojito',NULL,'9,50 €',110,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-12','getraenke-1','Cosmopolitan',NULL,'9,50 €',120,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-13','getraenke-1','Mai Tai',NULL,'9,50 €',130,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-14','getraenke-1','Espresso Martini',NULL,'9,50 €',140,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-15','getraenke-1','Tequila Sunrise',NULL,'9,50 €',150,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-16','getraenke-1','Planter´s Punch',NULL,'9,50 €',160,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-17','getraenke-1','Sex on the Beach',NULL,'9,50 €',170,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-18','getraenke-1','Piña Colada',NULL,'9,50 €',180,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-1-19','getraenke-1','Swimming Pool',NULL,'9,50 €',190,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-2','getraenke','Mocktails — alkoholfrei',NULL,20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-1','getraenke-2','Virgin Mojito',NULL,'6,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-2','getraenke-2','Virgin Caipi',NULL,'6,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-3','getraenke-2','Virgin Sunrise',NULL,'7,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-4','getraenke-2','Virgin Colada',NULL,'7,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-5','getraenke-2','Virgin on the Beach',NULL,'7,00 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-6','getraenke-2','Virgin Cosmo',NULL,'7,00 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-7','getraenke-2','Virgin Fizz',NULL,'8,00 €',70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-2-8','getraenke-2','Virgin Basil Smash',NULL,'8,00 €',80,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-3','getraenke','Spritz & Aperitif — 0,2 l',NULL,30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-1','getraenke-3','Aperol Spritz',NULL,'8,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-2','getraenke-3','Limoncello Spritz',NULL,'8,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-3','getraenke-3','Granatapfel Spritz',NULL,'8,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-4','getraenke-3','Campari Spritz',NULL,'8,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-5','getraenke-3','Spritz alkoholfrei',NULL,'8,00 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-6','getraenke-3','Roseano Wildberry / Tonic / Peach',NULL,'8,00 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-7','getraenke-3','Campari Orange',NULL,'8,00 €',70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-8','getraenke-3','Hugo / Hugo alkoholfrei',NULL,'8,00 €',80,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-9','getraenke-3','Pimm´s No.1 Cup / Pimp Pimm´s',NULL,'8,00 €',90,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-3-10','getraenke-3','London Mule / Moscow Mule','0,3 l','9,50 €',100,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-4','getraenke','Biere vom Fass — Hochdorfer',NULL,40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-4-1','getraenke-4','Pils','0,33 l / 0,5 l','4,00 € / 5,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-4-2','getraenke-4','Helles','0,33 l / 0,5 l','4,00 € / 5,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-4-3','getraenke-4','Weizen naturtrüb','0,33 l / 0,5 l','4,00 € / 5,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-4-4','getraenke-4','Radler','0,33 l / 0,5 l','4,00 € / 5,00 €',40,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-5','getraenke','Flaschenbiere',NULL,50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-5-1','getraenke-5','Kristallweizen','0,5 l','5,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-5-2','getraenke-5','Keller-Gold','0,5 l','5,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-5-3','getraenke-5','Naturradler','0,33 l — auch alkoholfrei','4,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-5-4','getraenke-5','Helles alkoholfrei','0,5 l','5,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-5-5','getraenke-5','Sportweizen alkoholfrei','0,5 l','5,00 €',50,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-6','getraenke','Weine aus der Region','Allmendinger · Weingärtner · Walz · Faigle — offen ab 0,1 l, Flasche 0,75 l.',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-1','getraenke-6','Riesling','Allmendinger · weiß, trocken · 0,1 l / 0,2 l / Schorle','4,00 € / 6,00 € / 5,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-2','getraenke-6','Weißburgunder','Allmendinger · weiß, trocken · 0,75 l','24,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-3','getraenke-6','Spätburgunder','Allmendinger · rosé, lieblich · 0,1 l / 0,2 l','4,00 € / 6,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-4','getraenke-6','Trollinger-Lemberger','Allmendinger · rot, trocken · 0,1 l / 0,2 l','4,00 € / 6,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-5','getraenke-6','Lemberger','Allmendinger · rot, trocken · 0,1 l / 0,2 l','4,50 € / 7,00 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-6','getraenke-6','Traminer','Weingärtner · weiß, halbtrocken · 0,75 l','24,00 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-7','getraenke-6','Lemberger Weißherbst','Weingärtner · rosé, feinherb · 0,1 l / 0,2 l / 0,75 l','4,00 € / 6,00 € / 21,50 €',70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-8','getraenke-6','Merlot rosé','Weingärtner · trocken · 0,75 l','21,50 €',80,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-9','getraenke-6','Chardonnay','Faigle · weiß, trocken · 0,1 l / 0,2 l / 0,75 l','4,50 € / 7,00 € / 24,00 €',90,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-10','getraenke-6','Muskat-Trollinger','Faigle · rosé, fruchtig · 0,1 l / 0,2 l / 0,75 l','4,50 € / 7,00 € / 24,00 €',100,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-11','getraenke-6','Grauburgunder','Der Fischer · weiß, trocken · 0,1 l / 0,2 l / 0,75 l','5,00 € / 8,00 € / 28,00 €',110,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-12','getraenke-6','Syrah','Der Fischer · rot, trocken · 0,75 l','32,00 €',120,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-6-13','getraenke-6','Sauvignon Blanc','Bodegas Salentine · weiß, halbtrocken · 0,75 l','28,00 €',130,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-7','getraenke','Schaumwein',NULL,70,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-7-1','getraenke-7','Sekt Hausmarke','0,1 l / 0,75 l','5,00 € / 19,50 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-7-2','getraenke-7','Zardetto Frizzante','Prosecco DOC brut · 0,75 l','24,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-7-3','getraenke-7','Zardetto Spumante','Prosecco DOC brut · 0,75 l','28,50 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-7-4','getraenke-7','Zardetto Rosé','Prosecco Millesimato DOC brut · 0,75 l','28,50 €',40,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-8','getraenke','Alkoholfrei',NULL,80,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-1','getraenke-8','Ensinger Bio-Gourmet still / medium','0,25 l / 0,75 l','3,00 € / 7,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-2','getraenke-8','Hausgemachte Limonade · 0 % Zucker','Himbeer-Zitrone · Pfirsich-Maracuja · Orange-Mango · Limette-Zitrone · Holunderblüte · 0,4 l','5,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-3','getraenke-8','Cola, Cola ohne Zucker, Orange, Zitrone','Afri/Bluna · 0,33 l','4,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-4','getraenke-8','Schweppes Tonic, Bitter Lemon, Ginger Ale, Wildberry','0,2 l','4,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-5','getraenke-8','Säfte & Nektare','Kumpf · Apfel, Orange, Ananas, Maracuja, Traube, Rhabarber, Cranberry · 0,2 l','4,00 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-8-6','getraenke-8','Schorle','0,2 l / 0,4 l','3,00 € / 4,50 €',60,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-9','getraenke','Kaffee & Tee',NULL,90,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-9-1','getraenke-9','Crema / Espresso',NULL,'3,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-9-2','getraenke-9','Espresso Macchiato',NULL,'3,50 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-9-3','getraenke-9','Espresso doppelt / Cappuccino',NULL,'4,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-9-4','getraenke-9','Affogato',NULL,'5,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-9-5','getraenke-9','Tee von der Sternschnuppe','Grüner Tee, Früchtetee, Rotbuschtee, Schwarzer Tee','4,00 €',50,1);
INSERT OR IGNORE INTO menu_groups (id,tab_id,title,note,sort,active) VALUES ('getraenke-10','getraenke','Spirituosen',NULL,100,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-1','getraenke-10','Gin','Gibson´s · Tanqueray Ten · Elephant · Hendrick´s · Monkey 47 · Roner Z44 · 4 cl','6,00 – 10,00 €',10,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-2','getraenke-10','Whisk(e)y','Canadian Club · Glen Moray · Bulleit · Suntory · Jura 12 · Dalmore 12 · 4 cl','6,00 – 12,00 €',20,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-3','getraenke-10','Rum','Flor de Caña · Saint James VSOP · Abuelo 7 · Ron Zacapa · 4 cl','6,00 – 10,00 €',30,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-4','getraenke-10','Wodka','Moskovskaya · Absolut · Ukiyo · Kaufmann · 4 cl','6,00 – 10,00 €',40,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-5','getraenke-10','Weinbrand','Asbach Uralt · Hennessy VS · Maison Gaultier · Adega Velha 12 XO · 4 cl','6,00 – 10,00 €',50,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-6','getraenke-10','Digestif & Likör','Obstler · Jägermeister · Erdbeerlimes · Ouzo 7 · Limoncello · Raki · Ramazotti','3,00 – 6,00 €',60,1);
INSERT OR IGNORE INTO menu_items (id,group_id,name,descr,price,sort,active) VALUES ('getraenke-10-7','getraenke-10','Wermut','Carpano Bianco / Rosso · Antico Formula · 6 cl','6,00 – 8,00 €',70,1);

INSERT OR IGNORE INTO settings (k,v) VALUES ('karte_stand','August 2026');
