-- Englische Karte und Bildzuordnung für die digitale Karte (/karte).
--
-- Nicht übersetzt und bewusst NULL: die 36 Cocktails, Mocktails und Spritz.
-- „Gin Basil Smash" heißt auf Englisch genauso, und eine Beschreibung haben sie
-- nicht. Die Seite fällt für diese Zeilen auf den deutschen Text zurück — das
-- ist der Grund, warum der Rückfall überhaupt eingebaut ist.
--
-- Eigennamen von Gerichten bleiben stehen (Maultaschen, Spätzle, Rostbraten,
-- Wiener Schnitzel, Manti). So steht es auch auf der englischen Karte eines
-- deutschen Hauses; erklärt wird in der Beschreibung.

UPDATE menu_tabs SET title_en = 'Starters & Salads' WHERE id = 'vorspeisen';
UPDATE menu_tabs SET title_en = 'Pasta & Noodles' WHERE id = 'teigwaren';
UPDATE menu_tabs SET title_en = 'Steak & Burger' WHERE id = 'steak';
UPDATE menu_tabs SET title_en = 'House Classics' WHERE id = 'klassiker';
UPDATE menu_tabs SET title_en = 'Desserts' WHERE id = 'suesses';
UPDATE menu_tabs SET title_en = 'Drinks' WHERE id = 'getraenke';
UPDATE menu_groups SET title_en = 'Soups' WHERE id = 'vorspeisen-1';
UPDATE menu_groups SET title_en = 'Starters' WHERE id = 'vorspeisen-2';
UPDATE menu_groups SET title_en = 'Salads' WHERE id = 'vorspeisen-3';
UPDATE menu_groups SET title_en = 'Pasta' WHERE id = 'teigwaren-1';
UPDATE menu_groups SET title_en = 'Swabian Noodles' WHERE id = 'teigwaren-2';
UPDATE menu_groups SET title_en = 'Steak on a hot stone' WHERE id = 'steak-1';
UPDATE menu_groups SET title_en = 'Burger' WHERE id = 'steak-2';
UPDATE menu_groups SET title_en = 'Sides' WHERE id = 'steak-3';
UPDATE menu_groups SET title_en = 'House Classics' WHERE id = 'klassiker-1';
UPDATE menu_groups SET title_en = 'Desserts' WHERE id = 'suesses-1';
UPDATE menu_groups SET title_en = 'Cocktails' WHERE id = 'getraenke-1';
UPDATE menu_groups SET title_en = 'Mocktails — alcohol-free' WHERE id = 'getraenke-2';
UPDATE menu_groups SET title_en = 'Spritz & Aperitif — 0.2 l' WHERE id = 'getraenke-3';
UPDATE menu_groups SET title_en = 'Draught beer — Hochdorfer' WHERE id = 'getraenke-4';
UPDATE menu_groups SET title_en = 'Bottled beer' WHERE id = 'getraenke-5';
UPDATE menu_groups SET title_en = 'Wines from the region' WHERE id = 'getraenke-6';
UPDATE menu_groups SET title_en = 'Sparkling' WHERE id = 'getraenke-7';
UPDATE menu_groups SET title_en = 'Soft drinks' WHERE id = 'getraenke-8';
UPDATE menu_groups SET title_en = 'Coffee & Tea' WHERE id = 'getraenke-9';
UPDATE menu_groups SET title_en = 'Spirits' WHERE id = 'getraenke-10';
UPDATE menu_items SET name_en = 'Cream of tomato soup', bild = 'tomatensuppe' WHERE id = 'vorspeisen-1-1';
UPDATE menu_items SET name_en = 'Lentil soup' WHERE id = 'vorspeisen-1-2';
UPDATE menu_items SET name_en = 'Beef consommé', descr_en = 'with a house-made Maultasche pasta pocket', bild = 'kraftbruehe' WHERE id = 'vorspeisen-1-3';
UPDATE menu_items SET name_en = 'Side salad' WHERE id = 'vorspeisen-2-1';
UPDATE menu_items SET name_en = 'Bruschetta', descr_en = 'with fresh rocket' WHERE id = 'vorspeisen-2-2';
UPDATE menu_items SET name_en = 'Buffalo mozzarella', descr_en = 'with house-made pesto, rocket and cherry tomatoes', bild = 'mozzarella' WHERE id = 'vorspeisen-2-3';
UPDATE menu_items SET name_en = 'Burrata', descr_en = 'with pan-fried courgette, tomatoes, rocket and pine nuts', bild = 'buratta' WHERE id = 'vorspeisen-2-4';
UPDATE menu_items SET name_en = 'Prawns', descr_en = 'with garlic, served in a clay pot', bild = 'garnelen' WHERE id = 'vorspeisen-2-5';
UPDATE menu_items SET name_en = 'Beef carpaccio', descr_en = 'with rocket, house-made pesto and Grana Padano', bild = 'carpaccio' WHERE id = 'vorspeisen-2-6';
UPDATE menu_items SET name_en = 'Salad Swabian style', descr_en = 'with house-made Maultaschen pasta pockets' WHERE id = 'vorspeisen-3-1';
UPDATE menu_items SET name_en = 'Salad Veggie', descr_en = 'with grilled vegetables and feta', bild = 'salat-veggie' WHERE id = 'vorspeisen-3-2';
UPDATE menu_items SET name_en = 'Salad Gambas', descr_en = 'with prawns and pineapple' WHERE id = 'vorspeisen-3-3';
UPDATE menu_items SET name_en = 'Salad Omega', descr_en = 'with salmon fillet and avocado', bild = 'salat-omega' WHERE id = 'vorspeisen-3-4';
UPDATE menu_items SET name_en = 'Salad Steakhouse', descr_en = 'with strips of beef steak', bild = 'salat-steakhouse' WHERE id = 'vorspeisen-3-5';
UPDATE menu_items SET name_en = 'Salad Wien', descr_en = 'with strips of breaded veal escalope' WHERE id = 'vorspeisen-3-6';
UPDATE menu_items SET name_en = 'Pasta Arrabbiata', descr_en = 'in a spicy tomato sauce', bild = 'pasta-arrabbiata' WHERE id = 'teigwaren-1-1';
UPDATE menu_items SET name_en = 'Pasta Caprese', descr_en = 'with buffalo mozzarella in a tomato cream sauce' WHERE id = 'teigwaren-1-2';
UPDATE menu_items SET name_en = 'Pasta Veggie', descr_en = 'with grilled vegetables in a tomato cream sauce' WHERE id = 'teigwaren-1-3';
UPDATE menu_items SET name_en = 'Pasta Gambas', descr_en = 'with prawns in a lime cream sauce', bild = 'pasta-gambas' WHERE id = 'teigwaren-1-4';
UPDATE menu_items SET name_en = 'Pasta Omega', descr_en = 'with salmon fillet and spinach in a white wine cream sauce', bild = 'pasta-omega' WHERE id = 'teigwaren-1-5';
UPDATE menu_items SET name_en = 'Pasta Steakhouse', descr_en = 'with strips of beef in a tomato cream sauce' WHERE id = 'teigwaren-1-6';
UPDATE menu_items SET name_en = 'Spätzle', descr_en = 'hand-scraped Swabian egg noodles with buttered onions' WHERE id = 'teigwaren-2-1';
UPDATE menu_items SET name_en = 'Käsespätzle', descr_en = 'hand-scraped egg noodles with Emmental, mountain cheese and buttered onions', bild = 'kaesespaetzle' WHERE id = 'teigwaren-2-2';
UPDATE menu_items SET name_en = 'Maultaschen', descr_en = 'house-made Swabian filled pasta pockets with buttered onions', bild = 'maultaschen' WHERE id = 'teigwaren-2-3';
UPDATE menu_items SET name_en = 'Manti', descr_en = 'small dumplings filled with minced meat, garlic yoghurt sauce and tomato butter', bild = 'manti' WHERE id = 'teigwaren-2-4';
UPDATE menu_items SET name_en = 'Sirloin steak', descr_en = 'lean and full-flavoured', bild = 'hueftsteak' WHERE id = 'steak-1-1';
UPDATE menu_items SET name_en = 'Rump steak', descr_en = 'with its characteristic rim of fat', bild = 'rumpsteak' WHERE id = 'steak-1-2';
UPDATE menu_items SET name_en = 'Fillet steak', descr_en = 'tender and lean', bild = 'filet' WHERE id = 'steak-1-3';
UPDATE menu_items SET name_en = 'Hamburger' WHERE id = 'steak-2-1';
UPDATE menu_items SET name_en = 'Cheeseburger', descr_en = 'with cheddar', bild = 'cheeseburger' WHERE id = 'steak-2-2';
UPDATE menu_items SET name_en = 'Chilli cheeseburger', descr_en = 'with cheddar and jalapeños' WHERE id = 'steak-2-3';
UPDATE menu_items SET name_en = 'BBQ burger', descr_en = 'with BBQ sauce and bacon', bild = 'bbq-burger' WHERE id = 'steak-2-4';
UPDATE menu_items SET name_en = 'Veggie burger', descr_en = 'with a vegetarian patty' WHERE id = 'steak-2-5';
UPDATE menu_items SET name_en = 'Extra patty' WHERE id = 'steak-2-6';
UPDATE menu_items SET name_en = 'Fries' WHERE id = 'steak-3-1';
UPDATE menu_items SET name_en = 'Sweet potato fries' WHERE id = 'steak-3-2';
UPDATE menu_items SET name_en = 'Vegetables' WHERE id = 'steak-3-3';
UPDATE menu_items SET name_en = 'Salad' WHERE id = 'steak-3-4';
UPDATE menu_items SET name_en = 'Swiss sausage salad', descr_en = 'sausage from Metzgerei Seyb with gherkins and Emmental', bild = 'wurstsalat' WHERE id = 'klassiker-1-1';
UPDATE menu_items SET name_en = 'Pork schnitzel, Viennese style', descr_en = 'house-made from the loin, with hand-scraped Spätzle or fries', bild = 'schnitzel-schwein' WHERE id = 'klassiker-1-2';
UPDATE menu_items SET name_en = 'Prawn pan', descr_en = 'prawns with grilled vegetables and basmati rice', bild = 'garnelenpfanne' WHERE id = 'klassiker-1-3';
UPDATE menu_items SET name_en = 'Beef pan', descr_en = 'sliced beef steak with grilled vegetables and basmati rice', bild = 'fleischpfanne' WHERE id = 'klassiker-1-4';
UPDATE menu_items SET name_en = 'Salmon fillet', descr_en = 'with spinach and basmati rice in a white wine sauce' WHERE id = 'klassiker-1-5';
UPDATE menu_items SET name_en = 'Rostbraten', descr_en = 'Swabian sirloin with crispy onions, a Maultasche and Lemberger jus, with hand-scraped Spätzle or pan-fried potatoes', bild = 'rostbraten' WHERE id = 'klassiker-1-6';
UPDATE menu_items SET name_en = 'Wiener Schnitzel of veal', descr_en = 'house-made from the loin, with cranberries and hand-scraped Spätzle or pan-fried potatoes', bild = 'schnitzel-kalb' WHERE id = 'klassiker-1-7';
UPDATE menu_items SET name_en = 'Sea bream fillet', descr_en = 'with grilled vegetables, pan-fried potatoes and a honey mustard sauce', bild = 'dorade' WHERE id = 'klassiker-1-8';
UPDATE menu_items SET name_en = 'Vanilla ice cream', descr_en = '2 scoops with chocolate or berry sauce' WHERE id = 'suesses-1-1';
UPDATE menu_items SET name_en = 'Panna cotta', descr_en = 'with house-made strawberry sauce, roasted hazelnuts and fresh strawberry', bild = 'panna-cotta' WHERE id = 'suesses-1-2';
UPDATE menu_items SET name_en = 'Crème brûlée', descr_en = 'house-made with lemon zest and vanilla', bild = 'creme-brulee' WHERE id = 'suesses-1-3';
UPDATE menu_items SET name_en = 'Hot berries', descr_en = '3 scoops of vanilla ice cream with hot berries and whipped cream', bild = 'heisse-beeren' WHERE id = 'suesses-1-4';
UPDATE menu_items SET name_en = 'Pancake', descr_en = 'with vanilla ice cream, berries, banana and house-made chocolate sauce' WHERE id = 'suesses-1-5';
UPDATE menu_items SET descr_en = '0.3 l' WHERE id = 'getraenke-3-10';
UPDATE menu_items SET descr_en = '0.33 l / 0.5 l' WHERE id = 'getraenke-4-1';
UPDATE menu_items SET descr_en = '0.33 l / 0.5 l' WHERE id = 'getraenke-4-2';
UPDATE menu_items SET name_en = 'Wheat beer, unfiltered', descr_en = '0.33 l / 0.5 l' WHERE id = 'getraenke-4-3';
UPDATE menu_items SET name_en = 'Shandy', descr_en = '0.33 l / 0.5 l' WHERE id = 'getraenke-4-4';
UPDATE menu_items SET name_en = 'Crystal wheat beer', descr_en = '0.5 l' WHERE id = 'getraenke-5-1';
UPDATE menu_items SET descr_en = '0.5 l' WHERE id = 'getraenke-5-2';
UPDATE menu_items SET name_en = 'Natural shandy', descr_en = '0.33 l — also alcohol-free' WHERE id = 'getraenke-5-3';
UPDATE menu_items SET name_en = 'Lager, alcohol-free', descr_en = '0.5 l' WHERE id = 'getraenke-5-4';
UPDATE menu_items SET name_en = 'Sports wheat beer, alcohol-free', descr_en = '0.5 l' WHERE id = 'getraenke-5-5';
UPDATE menu_items SET descr_en = 'Allmendinger · white, dry · 0.1 l / 0.2 l / spritzer' WHERE id = 'getraenke-6-1';
UPDATE menu_items SET name_en = 'Pinot Blanc', descr_en = 'Allmendinger · white, dry · 0.75 l' WHERE id = 'getraenke-6-2';
UPDATE menu_items SET name_en = 'Pinot Noir', descr_en = 'Allmendinger · rosé, sweet · 0.1 l / 0.2 l' WHERE id = 'getraenke-6-3';
UPDATE menu_items SET descr_en = 'Allmendinger · red, dry · 0.1 l / 0.2 l' WHERE id = 'getraenke-6-4';
UPDATE menu_items SET descr_en = 'Allmendinger · red, dry · 0.1 l / 0.2 l' WHERE id = 'getraenke-6-5';
UPDATE menu_items SET descr_en = 'Weingärtner · white, off-dry · 0.75 l' WHERE id = 'getraenke-6-6';
UPDATE menu_items SET name_en = 'Lemberger Weißherbst', descr_en = 'Weingärtner · rosé, medium-dry · 0.1 l / 0.2 l / 0.75 l' WHERE id = 'getraenke-6-7';
UPDATE menu_items SET descr_en = 'Weingärtner · dry · 0.75 l' WHERE id = 'getraenke-6-8';
UPDATE menu_items SET descr_en = 'Faigle · white, dry · 0.1 l / 0.2 l / 0.75 l' WHERE id = 'getraenke-6-9';
UPDATE menu_items SET descr_en = 'Faigle · rosé, fruity · 0.1 l / 0.2 l / 0.75 l' WHERE id = 'getraenke-6-10';
UPDATE menu_items SET name_en = 'Pinot Gris', descr_en = 'Der Fischer · white, dry · 0.1 l / 0.2 l / 0.75 l' WHERE id = 'getraenke-6-11';
UPDATE menu_items SET descr_en = 'Der Fischer · red, dry · 0.75 l' WHERE id = 'getraenke-6-12';
UPDATE menu_items SET descr_en = 'Bodegas Salentine · white, off-dry · 0.75 l' WHERE id = 'getraenke-6-13';
UPDATE menu_items SET name_en = 'House sparkling wine', descr_en = '0.1 l / 0.75 l' WHERE id = 'getraenke-7-1';
UPDATE menu_items SET descr_en = 'Prosecco DOC brut · 0.75 l' WHERE id = 'getraenke-7-2';
UPDATE menu_items SET descr_en = 'Prosecco DOC brut · 0.75 l' WHERE id = 'getraenke-7-3';
UPDATE menu_items SET descr_en = 'Prosecco Millesimato DOC brut · 0.75 l' WHERE id = 'getraenke-7-4';
UPDATE menu_items SET name_en = 'Ensinger mineral water, still / sparkling', descr_en = '0.25 l / 0.75 l' WHERE id = 'getraenke-8-1';
UPDATE menu_items SET name_en = 'House lemonade · no sugar', descr_en = 'raspberry-lemon · peach-passion fruit · orange-mango · lime-lemon · elderflower · 0.4 l' WHERE id = 'getraenke-8-2';
UPDATE menu_items SET name_en = 'Cola, sugar-free cola, orange, lemon', descr_en = 'Afri/Bluna · 0.33 l' WHERE id = 'getraenke-8-3';
UPDATE menu_items SET descr_en = '0.2 l' WHERE id = 'getraenke-8-4';
UPDATE menu_items SET name_en = 'Juices & nectars', descr_en = 'Kumpf · apple, orange, pineapple, passion fruit, grape, rhubarb, cranberry · 0.2 l' WHERE id = 'getraenke-8-5';
UPDATE menu_items SET name_en = 'Fruit juice spritzer', descr_en = '0.2 l / 0.4 l' WHERE id = 'getraenke-8-6';
UPDATE menu_items SET name_en = 'Coffee / Espresso' WHERE id = 'getraenke-9-1';
UPDATE menu_items SET name_en = 'Double espresso / Cappuccino' WHERE id = 'getraenke-9-3';
UPDATE menu_items SET name_en = 'Tea by Sternschnuppe', descr_en = 'green tea, fruit tea, rooibos, black tea' WHERE id = 'getraenke-9-5';
UPDATE menu_items SET descr_en = 'Gibson´s · Tanqueray Ten · Elephant · Hendrick´s · Monkey 47 · Roner Z44 · 4 cl' WHERE id = 'getraenke-10-1';
UPDATE menu_items SET descr_en = 'Canadian Club · Glen Moray · Bulleit · Suntory · Jura 12 · Dalmore 12 · 4 cl' WHERE id = 'getraenke-10-2';
UPDATE menu_items SET descr_en = 'Flor de Caña · Saint James VSOP · Abuelo 7 · Ron Zacapa · 4 cl' WHERE id = 'getraenke-10-3';
UPDATE menu_items SET name_en = 'Vodka', descr_en = 'Moskovskaya · Absolut · Ukiyo · Kaufmann · 4 cl' WHERE id = 'getraenke-10-4';
UPDATE menu_items SET name_en = 'Brandy', descr_en = 'Asbach Uralt · Hennessy VS · Maison Gaultier · Adega Velha 12 XO · 4 cl' WHERE id = 'getraenke-10-5';
UPDATE menu_items SET name_en = 'Digestif & Liqueur', descr_en = 'Obstler · Jägermeister · strawberry limes · Ouzo 7 · Limoncello · Raki · Ramazzotti' WHERE id = 'getraenke-10-6';
UPDATE menu_items SET name_en = 'Vermouth', descr_en = 'Carpano Bianco / Rosso · Antico Formula · 6 cl' WHERE id = 'getraenke-10-7';
